config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :working_times, only: %i[index new edit update create destroy] do
    collection do
      delete 'destroy_all'
    end
  end
  resources :day_offs, only: %i[new create]

  # Defines the root path route ("/")
  root 'working_times#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :tag_working_times, dependent: :destroy
  has_many :working_times, through: :tag_working_times

  validates :name, presence: true, uniqueness: true
end

app/models/tag_working_time.rb
# frozen_string_literal: true

class TagWorkingTime < ApplicationRecord
  belongs_to :tag
  belongs_to :working_time

  validates :tag_id, uniqueness: { scope: :working_time_id }
end

app/models/working_time.rb
# frozen_string_literal: true

class WorkingTime < ApplicationRecord
  HOURS_PER_DAY  = ENV.fetch('HOURS_PER_DAY', 8.2).to_f
  DAYS_PER_WEEK  = ENV.fetch('DAYS_PER_WEEK', 5).to_f
  HOURS_PER_WEEK = HOURS_PER_DAY * DAYS_PER_WEEK

  has_many :tag_working_times, dependent: :destroy
  has_many :tags, through: :tag_working_times

  validates :starts_at, presence: true

  def self.balance
    worked_time = all.sum(&:duration)
    return 0 if worked_time.zero?

    week_day = Time.current.wday.clamp(1, DAYS_PER_WEEK)
    remaining_time_for_week = ((DAYS_PER_WEEK - week_day) * HOURS_PER_DAY) * 3600

    worked_time + remaining_time_for_week - supposed_time_until_end_of_week
  end

  def self.supposed_time_until_end_of_week
    (all.group_by(&:week_date).count * HOURS_PER_WEEK) * 3600
  end

  def ongoing?
    ends_at.nil?
  end

  def duration
    (ends_at || Time.current).to_i - starts_at.to_i
  end

  def week_date
    starts_at.beginning_of_week
  end

  def tag_with(name)
    tags.find_or_create_by(name:)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/day_offs_controller.rb
# frozen_string_literal: true

class DayOffsController < ApplicationController
  def new
    @time = WorkingTime.new
  end

  def create
    day = Time.zone.parse working_time_params[:starts_at]

    @time = WorkingTime.new(
      starts_at: day + 8.hours,
      ends_at:   day + 16.5.hours
    )

    return redirect_to working_times_path if @time.save

    render :new
  end

  private

  def working_time_params
    params.permit!
    params[:working_time] || {}
  end
end

app/controllers/working_times_controller.rb
# frozen_string_literal: true

class WorkingTimesController < ApplicationController
  def index
    times = WorkingTime.includes(:tags).order(starts_at: :desc)
    @first_time = times.first
    @times = times
             .group_by { _1.starts_at.beginning_of_week }
             .transform_values do |week_working_times|
               week_working_times.group_by do |working_time|
                 working_time.starts_at.beginning_of_day
               end
    end
  end

  def new
    @time = WorkingTime.new
  end

  def edit
    time
  end

  def create
    @time = WorkingTime.new(
      starts_at: working_time_params[:starts_at] || Time.current,
      ends_at:   working_time_params[:ends_at]
    )

    return redirect_to working_times_path if @time.save

    render :new
  end

  def update
    time.tags = Tag.where(id: working_time_params[:tag_ids])
    time.update(
      starts_at: working_time_params[:starts_at] || time.starts_at,
      ends_at:   working_time_params[:ends_at] || Time.current
    )

    redirect_to working_times_path
  end

  def destroy
    time.destroy

    redirect_to working_times_path
  end

  def destroy_all
    WorkingTime.delete_all
    redirect_to working_times_path
  end

  private

  def time
    @time ||= WorkingTime.find(params[:id])
  end

  def working_time_params
    params.permit!
    params[:working_time] || {}
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_nav_tab_class
    'relative text-primary-700  after:absolute after:left-0 after:bottom-0 ' \
      'after:h-0.5 after:w-full after:bg-primary-700'
  end
end

app/helpers/working_times_helper.rb
# frozen_string_literal: true

module WorkingTimesHelper
  def relative_week(date)
    weeks = ActiveSupport::Duration.build(
      Time.current.beginning_of_week - date.beginning_of_week
    ).parts[:weeks]

    case weeks
    when nil
      'This week'
    when 1
      'Last week'
    when 2
      'Two weeks ago'
    else
      "Week #{date.strftime('%W')}"
    end + " / #{date.to_fs(:date)}"
  end

  def duration_to_hours_and_minutes(seconds)
    duration = to_duration(seconds)
    hours    = duration.in_hours.abs.floor
    minutes  = (duration.in_minutes.abs % 60).floor

    prefix = duration.negative? && !(minutes.zero? && hours.zero?) ? '-' : ''

    format_time(prefix, hours, minutes)
  end

  def format_time(prefix, hours, minutes)
    [
      ("#{hours}h" unless hours.zero?),
      ("#{minutes}min" if minutes.positive?)
    ].compact.join(' ').prepend(prefix).presence || '0min'
  end

  def week_duration_background(seconds)
    hours_per_week = WorkingTime::HOURS_PER_WEEK

    case to_duration(seconds).in_hours
    when ..(hours_per_week - 2)
      'bg-yellow-400'
    when ((hours_per_week + 2)..)
      'bg-red-500'
    else
      'bg-lime-500'
    end
  end

  private

  def to_duration(seconds)
    ActiveSupport::Duration.build(seconds)
  end
end

app/views/day_offs/new.html.slim
= turbo_frame_tag @time, class: 'grid-cols-subgrid grid col-start-1 col-end-6'
  = form_with model: @time,
              url:   day_offs_path,
              html:  { class: 'grid-cols-subgrid grid col-start-1 col-end-6' } do |f|
    .col-start-1.cell
    .col-start-2.cell
    .col-start-3.cell = f.date_field :starts_at, class: 'input'
    .col-start-4.cell.flex
      = render 'shared/form_buttons', form: f

app/views/layouts/application.html.slim
doctype html
html
  head
    title TimeTracker
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="view-transition" content="same-origin"
    meta name="turbo-refresh-method" content="morph"
    meta name="turbo-refresh-scroll" content="preserve"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body data-controller= "turbo-confirm"
    .m-4
      nav.mb-4.border-b.border-b-gray-100
        ul.-mb-px.flex.items-center.gap-4.text-sm.font-medium
          li = link_to 'Working times', root_path, class: "inline-flex cursor-pointer items-center gap-2 px-1 py-3 text-primary-700 hover:text-primary-700 #{active_nav_tab_class if current_page?(root_path)}"

      = yield

    = render 'shared/turbo_confirm_modal'

app/views/shared/_form_buttons.slim
.btn-group
  = link_to 'Cancel', root_path, class: 'btn-group__btn btn--secondary btn--sm'
  = form.submit 'Save', class: 'btn-group__btn btn--primary btn--sm', 'data-turbo-frame': '_top'

app/views/shared/_turbo_confirm_modal.html.slim
.fixed.inset-0.z-10.bg-secondary-700/50.hidden data-turbo-confirm-target="backdrop"

.fixed.inset-0.z-50.flex.items-center.justify-center.p-4.sm:p-0.hidden data-turbo-confirm-target="dialog"
  .mx-auto.w-full.overflow-hidden.rounded-lg.bg-white.shadow-xl.sm:max-w-sm
    .relative.p-5 data-form="destroy"
      .text-center
        h3.text-lg.font-medium.text-secondary-900 data-turbo-confirm-target="title"
        .mt-2.text-sm.text-secondary-500 data-turbo-confirm-target="body"
      form.mt-5.flex.justify-end.gap-3 method="dialog"
        button type="button" class="flex-1 btn btn--secondary" data-turbo-confirm-target="cancelButton" value="cancel" data-action="click->turbo-confirm#toggleModal"
        button type="button" class="flex-1 btn btn--danger" data-turbo-confirm-target="confirmButton" value="confirm"

app/views/working_times/_form.html.slim
= form_for @time, html: { class: 'grid-cols-subgrid grid col-start-1 col-end-6' } do |f|
  .col-start-1.cell = f.datetime_field :starts_at, include_seconds: false, class: 'input'
  .col-start-2.cell = f.datetime_field :ends_at, include_seconds: false, class: 'input'
  .col-start-3.cell
    = f.collection_select :tag_ids, Tag.all, :id, :name, { include_blank: true },
      { multiple: true, class: 'input h-8' }
  .col-start-4.cell.flex
    = render 'shared/form_buttons', form: f

app/views/working_times/edit.html.slim
= turbo_frame_tag @time
  = render 'form'

app/views/working_times/index.html.slim
.w-full.text-left.grid.grid-cols-5.text-sm.divide-y.divide-gray-100.border-t.border-gray-100
  = turbo_frame_tag WorkingTime.new, class: 'grid-cols-subgrid grid col-start-1 col-end-6'
    .cell.col-start-1.rounded-md.bg-primary-50.p-4.text-sm.text-primary-500.flex-col.gap-2.items-start
      .flex.gap-2
        = 'Hours/week with break:'
        span.font-bold = WorkingTime::HOURS_PER_WEEK
      .flex.gap-2
        = 'Balance:'
        span.font-bold = duration_to_hours_and_minutes WorkingTime.balance
    .cell.col-start-4.col-span-2.flex.items-center
      .btn-group
        ruby:
          label, path, method, klass =
            if @first_time&.ongoing?
              ['Stop', working_time_path(@first_time), :patch, "btn--danger"]
            else
              ['Start', working_times_path(WorkingTime.new), :post, "btn--success"]
            end
        = button_to label, path,
          method:,
          class: "btn-group__btn #{klass}",
          'data-turbo-frame': '_top'
        = link_to 'New', new_working_time_path, class: 'btn-group__btn btn--primary'
        = link_to 'Day off', new_day_off_path, class: 'btn-group__btn btn--secondary'
        = button_to 'Clear all times', destroy_all_working_times_path,
          method: :delete,
          class: 'btn-group__btn btn--danger',
          'data-turbo-confirm': 'true',
          'data-turbo-frame': '_top',
          form: { 'data-confirm-body': "Are you sure you want to delete all working times?",
                  'data-confirm-label': "Delete" }

  .cell.bg-gray-100 Starts at
  .cell.bg-gray-100 Ends at
  .cell.bg-gray-100 Duration
  .cell.bg-gray-100
  .cell.bg-gray-100 Tags

  - @times.each_pair.each do |monday, week_times|
    .cell.bg-gray-300 = relative_week monday
    .bg-gray-300
    - week_duration = week_times.values.flatten.sum(&:duration)
    .cell class=week_duration_background(week_duration)
      = duration_to_hours_and_minutes week_duration
    .bg-gray-300
    .bg-gray-300

    - week_times.each do |day, day_times|
      .cell.col-span-2.bg-gray-100 = day.to_fs :week_day
      .cell.col-span-3.bg-gray-100= duration_to_hours_and_minutes day_times.sum(&:duration)

      - day_times.each do |time|
        = turbo_frame_tag time, class: "grid grid-cols-subgrid col-start-1 col-end-6 #{'bg-orange-200' if time.ongoing?}"
          .cell.col-start-1 = time.starts_at.to_fs :time
          .cell.col-start-2
            span class="#{'rounded-full bg-red-50 px-2 py-1 text-xs font-semibold text-red-600' if time.ongoing?}"
              = time.ends_at&.to_fs(:time) || 'ongoing'
          .cell.col-start-3 = duration_to_hours_and_minutes time.duration
          .cell.col-start-4.flex.gap-2
            = link_to 'Edit', edit_working_time_path(time),
              method: :get, class: 'btn btn--sm btn--primary'

            = button_to 'X', working_time_path(time),
              method: :delete,
              class: 'btn btn--sm btn--danger',
              'data-turbo-confirm': 'true',
              'data-turbo-frame': '_top',
              form: { 'data-confirm-body': "Are you sure you want to delete this working time?",
                      'data-confirm-label': "Delete" }
          .cell.col-start-5
            - time.tags.each do |tag|
              span.rounded-full.bg-green-50.px-2.py-1.text-xs.font-semibold.text-green-600 = tag.name

app/views/working_times/new.html.slim
h1 New Working Time

= turbo_frame_tag @time, class: 'grid-cols-subgrid grid col-start-1 col-end-5'
  = render 'form'